### PR TITLE
Adapt MetaFactory to DefaultFactory

### LINKED ISSUE #72: Create broken after DefaultFactory extraction
## Describe the bug
The tests worked for the DefaultFactory but it didn't for the MetaFactory.

## Error message
```
TypeError: this.factory.createShape is not a function
```

## To Reproduce
1. Try to place a figure with the CreateTool

## Expected behavior
CreateTool should be activated

## Environment
 - OS: Windows
 - Browser Firefox
 - Version 66.0.1

## Additional context
Create test to ensure behavior for the MetaFactory

### PR DESCRIPTION
**Pull request by tim-kilian**
Closes #72 

## Describe your changes
- Adapted MetaFactory so it uses it's createConnection / createShape / createLabel methods in create connect modules

## Open 
- [x] Add tests to ensure behavior for feature changes.

### CODE REVIEW

**Comment by tim-kilian** [comment]
I've created a `FactoryModule` and extracted all Factory dependencies to this module, but also created a `MetaFactoryModule` for a more specific factory. They are both included in the DrawModule and can be interchangeable with the `FactoryProvider`. 

I've also added a current shape to the metaFactory so its creating a cached shape, so no parameter is nessesary so the 3 abstract methods (`createShape`, `createConnection`, `createLabel`) can be called on all of them.

I've added a TestPlugin to test the meta behaviors without an extern plugin.

**Comment by 0x4d** [comment]
> I've created a `FactoryModule` and extracted all Factory dependencies to this module, but also created a `MetaFactoryModule` for a more specific factory. They are both included in the DrawModule and can be interchangeable with the `FactoryProvider`.

Great rework, the whole structure is much more coherent now :smile:

**Comment by 0x4d** [comment]
> I've added a TestPlugin to test the meta behaviors without an extern plugin.

Thanks for this, I'm gonna use it to add tests to meta import and export behaviors (#51).

**Review by 0x4d — APPROVED** [review]
:+1:

**Pull request merged**
